name: onimo
description: An anonymous chat.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.19.2 <3.0.0"

dependencies:
  firebase_app_check: ^0.1.1+12
  firebase_core: ^2.7.0
  firebase_database: ^10.0.14
  flutter:
    sdk: flutter
  intl: ^0.18.0
  substring_highlight: ^1.0.33

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
