name: onimo
description: An anonymous chat.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.19.2 <3.0.0"

dependencies:
  cryptography_flutter: ^2.3.0
  firebase_app_check: ^0.1.1+13
  firebase_core: ^2.7.1
  firebase_database: ^10.0.15
  flutter:
    sdk: flutter
  get_it: ^7.2.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.18.0
  meta: ^1.8.0
  mobx: ^2.1.4
  substring_highlight: ^1.0.33

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mobx_codegen: ^2.1.1
  build_runner: ^2.3.3

flutter:
  uses-material-design: true
