class Constants {
  static const List<String> letters = [
    'a',
    'b',
    'c',
    'd',
    'e',
    'f',
    'g',
    'h',
    'i',
    'j',
    'k',
    'l',
    'm',
    'n',
    'o',
    'p',
    'q',
    'r',
    's',
    't',
    'u',
    'v',
    'w',
    'x',
    'y',
    'z',
  ];

  static const List<String> digits = [
    '0',
    '1',
    '2',
    '3',
    '4',
    '5',
    '6',
    '7',
    '8',
    '9',
  ];

  static const List<String> nicknames = [
    "pixel_art",
    "byte_code",
    "hacker_ninja",
    "cyber_shadow",
    "grey_hat",
    "robot_warrior",
    "web_master",
    "cmd_hacker",
    "byte_hacker",
    "john_doe",
    "pixel_ninja",
    "code_hunter",
    "tech_master",
    "windows_lover",
    "metal_head",
    "white_hat",
    "data_genius",
    "mr_coder",
    "noob_lammer",
    "byte_king",
    "pixel_coder",
    "tech_dragon",
    "blank_code",
    "linux_lover",
    "script_kiddie",
    "hacker_owl",
    "black_hat",
    "mr_robot",
    "data_seeker",
    "kali_linux"
  ];

  static const List<String> rules = [
    'Preste respeito a todos os usuários.',
    'Não revele sua verdadeira identidade.',
    'Não divulgue suas informações pessoais, como endereço, número de telefone, documentos e etc.',
    'Não divulgue conteúdos ilícitos, ofensivos, violentos, sexuais, e dentre outros desconfortáveis ou repudiantes.',
    'Não utilize o chat para fins comerciais ou publicitários.',
    'Não use linguagem abusiva ou palavrões.',
    'Embora o chat seja anônimo, suas ações podem ser rastreadas e, se necessário, medidas legais podem ser tomadas.',
  ];

  static const List<String> information = [
    'Todos os dias você recebe um novo "apelido de usuário" pré-definido. Ele estará situado no canto superior esquerdo da tela principal.',
    'Não é possível alterar seu apelido de usuário manualmente.',
    'É possível criar no máximo 10 salas públicas, cada uma comportando 5 usuários simultaneamente.',
    'Salas privadas comportam no máximo 10 usuários simultaneamente.',
    'Quando todos os usuários de uma sala privada se desconectam, ela será excluída automaticamente.',
    'Todas as salas e mensagens são deletadas automaticamente às 00:00h.'
  ];
}
